version: '3'
services:
  frontend:
    build: .
    command: gunicorn --reload --bind 0.0.0.0:8000 --access-logfile - wsgi
    tty: true
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
